### PR TITLE
Changes for Embarcadero C++ clang-based compilers, targeting Boost 1.74. Change __BORLANDC__ to BOOST_BORLANDC, which is defined in Boost conf…

### PR DESCRIPTION
**Pull request by eldiener**
…ig for the Embarcadero non-clang-based compilers.

### CODE REVIEW

**Comment by vinniefalco** [comment]
The commit does not have the correct email and credentials, which is why GitHub isn't hyperlinking it to the maintainer's account. This is caused by an incorrect local Git configuration. Use `git config` for the relevant settings to resolve.

**Comment by eldiener** [comment]
> 
> 
> The commit does not have the correct email and credentials, which is why GitHub isn't hyperlinking it to the maintainer's account. This is caused by an incorrect local Git configuration. Use `git config` for the relevant settings to resolve.

Where in the commit does it show the email and credentials which you are talking about ?

**Comment by vinniefalco** [comment]
image

**Comment by vinniefalco** [comment]
Note the email associated with the commit:

image

**Comment by eldiener** [comment]
It is still a valid email account for me. Like many people I have more than one email address.

**Comment by mloskot** [comment]
@eldiener

https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/adding-an-email-address-to-your-github-account

**Comment by vinniefalco** [comment]
Looks better now :)

**Pull request merged**
